version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: textile_waste_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: textile_admin
      POSTGRES_PASSWORD: textile_pass
      POSTGRES_DB: textile_waste
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongo:
    image: mongo:7
    container_name: textile_waste_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  pgdata:
  mongodata:
