"""
Recycling Recommendations Router
Exposes aggregated recommendation data from persisted AnalysisResult records.

Does NOT reimplement recommendation logic — uses outputs already
generated by recyclability_service.py and stored in PostgreSQL.
"""

import logging
from fastapi import APIRouter, Depends
from sqlalchemy.orm import Session
from sqlalchemy import func as sqlfunc

from app.database import get_db
from app.middleware.auth_middleware import get_current_active_user
from app.models.user import User
from app.models.analysis_result import AnalysisResult

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/recommendations", tags=["Recycling Recommendations"])


@router.get("/summary")
async def get_recommendations_summary(
    current_user: User = Depends(get_current_active_user),
    db: Session = Depends(get_db),
):
    """
    Aggregated recycling recommendation statistics from all analysis records.

    Returns:
    - Total analyses
    - Primary recycling strategy distribution
    - Most common strategy
    - Reuse potential distribution
    - Waste category distribution
    """
    total = db.query(AnalysisResult).count()

    if total == 0:
        return {
            "total_analyses": 0,
            "message": "No analysis records found. Run analyses to populate this data.",
            "strategy_distribution": {},
            "most_common_strategy": None,
            "reuse_potential_distribution": {},
            "waste_category_distribution": {},
        }

    # Strategy distribution
    strategy_rows = (
        db.query(
            AnalysisResult.primary_recycling_strategy,
            sqlfunc.count(AnalysisResult.id).label("count"),
        )
        .filter(AnalysisResult.primary_recycling_strategy.isnot(None))
        .group_by(AnalysisResult.primary_recycling_strategy)
        .order_by(sqlfunc.count(AnalysisResult.id).desc())
        .all()
    )
    strategy_distribution = {row[0]: row[1] for row in strategy_rows}
    most_common_strategy = strategy_rows[0][0] if strategy_rows else None

    # Reuse potential distribution
    reuse_rows = (
        db.query(
            AnalysisResult.reuse_potential,
            sqlfunc.count(AnalysisResult.id).label("count"),
        )
        .filter(AnalysisResult.reuse_potential.isnot(None))
        .group_by(AnalysisResult.reuse_potential)
        .order_by(sqlfunc.count(AnalysisResult.id).desc())
        .all()
    )
    reuse_potential_distribution = {row[0]: row[1] for row in reuse_rows}

    # Waste category distribution
    category_rows = (
        db.query(
            AnalysisResult.waste_category,
            sqlfunc.count(AnalysisResult.id).label("count"),
        )
        .filter(AnalysisResult.waste_category.isnot(None))
        .group_by(AnalysisResult.waste_category)
        .order_by(sqlfunc.count(AnalysisResult.id).desc())
        .all()
    )
    waste_category_distribution = {row[0]: row[1] for row in category_rows}

    # Condition distribution
    condition_rows = (
        db.query(
            AnalysisResult.condition,
            sqlfunc.count(AnalysisResult.id).label("count"),
        )
        .filter(AnalysisResult.condition.isnot(None))
        .group_by(AnalysisResult.condition)
        .all()
    )
    condition_distribution = {row[0]: row[1] for row in condition_rows}

    return {
        "total_analyses": total,
        "strategy_distribution": strategy_distribution,
        "most_common_strategy": most_common_strategy,
        "reuse_potential_distribution": reuse_potential_distribution,
        "waste_category_distribution": waste_category_distribution,
        "condition_distribution": condition_distribution,
    }