# Generated by Django 5.2.16 on 2026-07-11 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TextileWaste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('material_type', models.CharField(choices=[('Cotton', 'Cotton'), ('Polyester', 'Polyester'), ('Silk', 'Silk'), ('Wool', 'Wool'), ('Denim', 'Denim')], max_length=100)),
                ('quantity', models.FloatField()),
                ('color', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=100)),
                ('condition', models.CharField(choices=[('New Surplus', 'New Surplus'), ('Lightly Used', 'Lightly Used'), ('Worn', 'Worn'), ('Damaged', 'Damaged'), ('Contaminated', 'Contaminated')], default='Worn', max_length=20)),
                ('collection_date', models.DateField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waste_batches', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Recycling Facility Operator', 'Recycling Facility Operator'), ('Sustainability Manager', 'Sustainability Manager'), ('Textile Manufacturer Administrator', 'Textile Manufacturer Administrator')], max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
