# Generated by Django 5.2.16 on 2026-07-26 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='textilewaste',
            name='status',
            field=models.CharField(choices=[('Registered', 'Registered'), ('Processing', 'Processing'), ('Recycled', 'Recycled'), ('Disposed', 'Disposed')], default='Registered', max_length=20),
        ),
    ]
