# Generated by Django 5.2.16 on 2026-07-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_textilewaste_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='textilewaste',
            name='circularity_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='textilewaste',
            name='detected_material',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='textilewaste',
            name='waste_category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
