# Generated by Django 5.2.16 on 2026-08-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_textilewaste_circularity_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textilewaste',
            name='status',
            field=models.CharField(choices=[('Registered', 'Registered'), ('Collected', 'Collected'), ('In Processing', 'In Processing'), ('Processed', 'Processed')], default='Registered', max_length=20),
        ),
    ]
