import { jsPDF } from "jspdf";

const GREEN = [46, 125, 50];
const LIGHT_GREEN = [232, 245, 233];
const GRAY = [107, 114, 128];
const LIGHT_GRAY = [245, 245, 245];
const DARK = [26, 26, 26];

function fileToDataUrl(file) {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => resolve(reader.result);
    reader.onerror = reject;
    reader.readAsDataURL(file);
  });
}

function drawSectionTitle(doc, title, x, y) {
  doc.setDrawColor(...GREEN);
  doc.setLineWidth(0.5);
  doc.line(x, y + 6, x + 220, y + 6);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(13);
  doc.setTextColor(...GREEN);
  doc.text(title, x, y);

  return y + 20;
}

function drawInfoBox(doc, x, y, width, height) {
  doc.setFillColor(...LIGHT_GRAY);
  doc.roundedRect(x, y, width, height, 6, 6, "F");
}

function drawKeyValue(doc, label, value, x, y, wrap = 320) {
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.setTextColor(...GRAY);
  doc.text(label + ":", x, y);

  doc.setFont("helvetica", "normal");
  doc.setTextColor(...DARK);

  const lines = doc.splitTextToSize(String(value || "-"), wrap);

  doc.text(lines, x + 95, y);

  return y + lines.length * 14 + 8;
}

function drawSummaryCard(doc, x, y, title, value) {
  doc.setFillColor(...LIGHT_GREEN);
  doc.roundedRect(x, y, 120, 60, 6, 6, "F");

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...GRAY);
  doc.text(title, x + 10, y + 18);

  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(...GREEN);
  doc.text(String(value), x + 10, y + 42);
}

function drawProgressBar(doc, x, y, width, percent) {
  doc.setFillColor(225,225,225);
  doc.roundedRect(x, y, width, 8, 4, 4, "F");

  doc.setFillColor(...GREEN);
  doc.roundedRect(
    x,
    y,
    width * Math.min(percent,100) / 100,
    8,
    4,
    4,
    "F"
  );
}

function addFooter(doc) {
  const pages = doc.getNumberOfPages();

  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);

    const w = doc.internal.pageSize.getWidth();
    const h = doc.internal.pageSize.getHeight();

    doc.setDrawColor(220);
    doc.line(40, h - 34, w - 40, h - 34);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(...GRAY);

    doc.text(
      "Generated by AI Textile Waste Intelligence Platform",
      40,
      h - 18
    );

    doc.text(
      `Page ${i} of ${pages}`,
      w - 90,
      h - 18
    );
  }
}

async function drawPredictionPage(doc, params) {
  const {
    imageFile,
    material,
    confidence,
    wasteCategory,
    recyclability,
    recommendation,
    top3Predictions = [],
    materialTypeInfo,
    processingTimeSeconds,
    headerSubtitle,
  } = params;

  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();

  const margin = 40;

  // ================= HEADER =================
  doc.setFillColor(...GREEN);
  doc.rect(0, 0, pageWidth, 70, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(255,255,255);
  doc.text("AI Textile Waste Intelligence Platform", margin, 28);

  doc.setFontSize(12);
  doc.setFont("helvetica","normal");
  doc.text("Fabric Prediction Report", margin, 48);

  doc.setFontSize(9);
  doc.text(
      headerSubtitle || new Date().toLocaleString(),
      pageWidth-180,
      48
  );

  let y = 95;

  // ================= IMAGE =================
  if(imageFile){

      try{

          const img = await fileToDataUrl(imageFile);

          const type=imageFile.type.includes("png")?"PNG":"JPEG";

          const imgWidth = 150;

          const imgHeight = 150;

          doc.addImage(
              img,
              type,
              margin,
              y,
              imgWidth,
              imgHeight,
              undefined,
              "FAST"
          );

      }catch(e){}
  }

  // ================= MATERIAL =================

  const textX = 220;

  doc.setFont("helvetica","bold");
  doc.setFontSize(22);
  doc.setTextColor(...DARK);
  doc.text(material,textX,y+20);

  // Confidence Badge

  doc.setFillColor(...LIGHT_GREEN);

  doc.roundedRect(textX,y+40,95,26,6,6,"F");

  doc.setFont("helvetica","bold");
  doc.setFontSize(12);
  doc.setTextColor(...GREEN);
  doc.text(`${confidence}%`,textX+30,y+58);

  if(processingTimeSeconds!=null){

      doc.setFont("helvetica","normal");
      doc.setFontSize(10);
      doc.setTextColor(...GRAY);

      doc.text(
          `Processing Time : ${processingTimeSeconds.toFixed(2)} sec`,
          textX,
          y+90
      );
  }

  y+=175;

  // ================= Waste Box =================

  y=drawSectionTitle(doc,"Waste & Recycling",margin,y);

  drawInfoBox(doc,margin,y,pageWidth-80,85);

  let yy=y+20;

  yy=drawKeyValue(doc,"Waste Category",wasteCategory,margin+12,yy);

  yy=drawKeyValue(doc,"Recyclability",recyclability,margin+12,yy);

  yy=drawKeyValue(
      doc,
      "Recommendation",
      recommendation,
      margin+12,
      yy,
      pageWidth-220
  );

  y+=105;

  // ================= Fabric Info =================

  if(materialTypeInfo){

      y=drawSectionTitle(doc,"Fabric Information",margin,y);

      drawInfoBox(doc,margin,y,pageWidth-80,110);

      let fy=y+20;

      fy=drawKeyValue(
          doc,
          "Material Type",
          materialTypeInfo.type,
          margin+12,
          fy
      );

      fy=drawKeyValue(
          doc,
          "Common Uses",
          materialTypeInfo.commonUses,
          margin+12,
          fy
      );

      fy=drawKeyValue(
          doc,
          "Description",
          materialTypeInfo.description,
          margin+12,
          fy,
          pageWidth-220
      );

      y+=130;
  }

  // ================= Top 3 =================

  if(top3Predictions.length){

      y=drawSectionTitle(doc,"Top 3 Predictions",margin,y);

      top3Predictions.forEach((item)=>{

          doc.setFontSize(11);
          doc.setTextColor(...DARK);

          doc.text(item.material,margin,y);

          drawProgressBar(
              doc,
              margin+120,
              y-6,
              180,
              item.confidence
          );

          doc.text(
              `${item.confidence}%`,
              margin+315,
              y
          );

          y+=20;

      });

  }

  addFooter(doc);
}

export async function downloadPredictionPdf({
  imageFile,
  material,
  confidence,
  wasteCategory,
  recyclability,
  recommendation,
  top3Predictions = [],
  materialTypeInfo,
  processingTimeSeconds,
  fileName,
}) {
  const doc = new jsPDF({
    unit: "pt",
    format: "a4",
  });

  await drawPredictionPage(doc, {
    imageFile,
    material,
    confidence,
    wasteCategory,
    recyclability,
    recommendation,
    top3Predictions,
    materialTypeInfo,
    processingTimeSeconds,
  });

  addFooter(doc);

  doc.save(
    fileName ||
      `fabric_prediction_${material.toLowerCase()}_${Date.now()}.pdf`
  );
}

export async function downloadBatchPredictionsReport(
  items,
  summary = {},
  fileName
) {
  if (!items || items.length === 0) return;

  const doc = new jsPDF({
    unit: "pt",
    format: "a4",
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 40;

  // COVER PAGE
  doc.setFillColor(...GREEN);
  doc.rect(0, 0, pageWidth, 100, "F");

  doc.setFont("helvetica", "bold");
  doc.setFontSize(24);
  doc.setTextColor(255, 255, 255);
  doc.text(
    "AI Textile Waste Intelligence Platform",
    margin,
    40
  );

  doc.setFontSize(15);
  doc.text(
    "Batch Prediction Report",
    margin,
    66
  );

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(
    new Date().toLocaleString(),
    margin,
    84
  );

  // SUMMARY
  drawSummaryCard(
    doc,
    40,
    140,
    "Total Images",
    summary.total ?? items.length
  );

  drawSummaryCard(
    doc,
    180,
    140,
    "Processed",
    summary.processed ?? items.length
  );

  drawSummaryCard(
    doc,
    320,
    140,
    "Avg Confidence",
    summary.avgConfidence != null
      ? `${summary.avgConfidence}%`
      : "-"
  );

  drawSummaryCard(
    doc,
    460,
    140,
    "Recyclable",
    summary.recyclableCount ?? "-"
  );

  // EXTRA STATISTICS
  let y = 250;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(...GREEN);
  doc.text("Batch Statistics", margin, y);

  y += 25;

  const materials = {};

  let highest = items[0];
  let lowest = items[0];

  items.forEach((item) => {
    materials[item.material] =
      (materials[item.material] || 0) + 1;

    if (item.confidence > highest.confidence)
      highest = item;

    if (item.confidence < lowest.confidence)
      lowest = item;
  });

  const mostCommon = Object.keys(materials).reduce(
    (a, b) =>
      materials[a] > materials[b]
        ? a
        : b
  );

  y = drawKeyValue(
    doc,
    "Most Common Material",
    mostCommon,
    margin,
    y
  );

  y = drawKeyValue(
    doc,
    "Highest Confidence",
    `${highest.material} (${highest.confidence}%)`,
    margin,
    y
  );

  y = drawKeyValue(
    doc,
    "Lowest Confidence",
    `${lowest.material} (${lowest.confidence}%)`,
    margin,
    y
  );

  y = drawKeyValue(
    doc,
    "Different Materials",
    Object.keys(materials).length,
    margin,
    y
  );

  // INCLUDED FILES
  y += 25;

  doc.setFont("helvetica", "bold");
  doc.setFontSize(14);
  doc.setTextColor(...GREEN);
  doc.text(
    "Included Predictions",
    margin,
    y
  );

  y += 25;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(...DARK);

  items.forEach((item, index) => {

    if (
      y >
      doc.internal.pageSize.getHeight() - 70
    ) {
      doc.addPage();
      y = 50;
    }

    doc.text(
      `${index + 1}. ${item.material} (${item.confidence}%)`,
      margin,
      y
    );

    y += 16;

  });

  // DETAIL PAGES
  for (let i = 0; i < items.length; i++) {

    doc.addPage();

    await drawPredictionPage(doc, {
      ...items[i],
      headerSubtitle: `Prediction ${i + 1} of ${items.length}`,
    });

  }

  addFooter(doc);

  doc.save(
    fileName ||
      `Batch_Prediction_Report_${Date.now()}.pdf`
  );
}