# Generated by Django 5.2.16 on 2026-07-29 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0002_textilewaste_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpactRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co2_saved_kg', models.FloatField(default=0)),
                ('water_saved_liters', models.FloatField(default=0)),
                ('circularity_score', models.FloatField(default=0)),
                ('recommended_strategy', models.CharField(blank=True, max_length=100)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('waste_batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='impact', to='inventory.textilewaste')),
            ],
        ),
    ]
